### ISSUE TITLE
Bug al ejecutar un flujo de cargas con visualizacion

### ISSUE THREAD

**Issue by fernpos** [SanPen/GridCal#274]
Problema cuando estoy visulizando el resultado de un flujo de cargas en el snapshot. Me traigo otra hora al snapshot, y luego ejecuto un flujo de cargas.
Code:
Traceback (most recent call last):
  File "C:\ReposGit\github\fernpos\GridCal5\src\GridCal\Gui\Main\SubClasses\Model\time_events.py", line 471, in set_profile_state_to_snapshot
    self.circuit.set_state(t=idx)
  File "C:\ReposGit\github\fernpos\GridCal5\src\GridCalEngine\Devices\multi_circuit.py", line 4447, in set_state
    elm.set_profile_values(t)
  File "C:\ReposGit\github\fernpos\GridCal5\src\GridCalEngine\Devices\Parents\editable_device.py", line 621, in set_profile_values
    setattr(self, magnitude, profile[t])
  File "C:\ReposGit\github\fernpos\GridCal5\src\GridCalEngine\Devices\Parents\injection_parent.py", line 131, in bus
    raise Exception(str(type(val)) + 'not supported to be set into a bus')
Exception: <class 'str'>not supported to be set into a bus

**Comment by SanPen** [comment]
Resuelto aquí: [1cfbfa2](https://github.com/SanPen/GridCal/commit/1cfbfa2625ca36c1413efaf300b8b5edaf8d7472)
